import { mockDb } from './mockDb'
import { ensureIdentitiesForOrg } from './deviceIdentity'
import {
  ensureWalletsForOrg,
  getWallet,
  listTransactions,
  transfer,
  setWallet,
} from './deviceWallet'
import {
  CAPABILITY_TEMPLATES,
  createCapability,
  listCapabilities,
  type CapabilityTemplate,
} from './capabilities'
import {
  listNegotiations,
  saveNegotiation,
  type Negotiation,
  type NegotiationRound,
} from './negotiationEngine'
import {
  createContract,
  listContracts,
} from './contracts'
import { createRating, listRatings } from './thingRating'
import { pushNotification, loadNotifications } from './rulesEngine'
import { getDidFor } from './deviceIdentity'

const SEED_FLAG_KEY = 'thingdaddy.economy.seed.v1'
const MILESIGHT_ORG_ID = 'org_00000006-0000-0000-0000-000000000006'

function isBrowser(): boolean {
  return typeof window !== 'undefined'
}

function tpl(name: string): CapabilityTemplate {
  const found = CAPABILITY_TEMPLATES.find((t) => t.name === name)
  if (!found) throw new Error(`capability template not found: ${name}`)
  return found
}

function iso(offset: number): string {
  // offset in minutes, negative = in the past
  return new Date(Date.now() + offset * 60_000).toISOString()
}

function seedNegotiationRecord(opts: {
  id: string
  orgId: string
  buyerThingId: string
  sellerThingId: string
  capabilityId: string
  capabilityName: string
  capabilityIcon: string
  unit: string
  listedPrice: number
  buyerBudget: number
  sellerMinAccept: number
  rounds: Array<Omit<NegotiationRound, 'timestamp' | 'autoGenerated'> & { minutesAgo: number }>
  agreedPrice: number
  startedMinutesAgo: number
  strategy: Negotiation['buyerStrategy']
  sellerStrategy: Negotiation['sellerStrategy']
  contractDuration: string
  status?: Negotiation['status']
}): Negotiation {
  const neg: Negotiation = {
    id: opts.id,
    orgId: opts.orgId,
    buyerThingId: opts.buyerThingId,
    buyerDid: getDidFor(opts.buyerThingId),
    sellerThingId: opts.sellerThingId,
    sellerDid: getDidFor(opts.sellerThingId),
    capabilityId: opts.capabilityId,
    capabilityName: opts.capabilityName,
    capabilityIcon: opts.capabilityIcon,
    unit: opts.unit,
    listedPrice: opts.listedPrice,
    buyerBudget: opts.buyerBudget,
    sellerMinAccept: opts.sellerMinAccept,
    buyerStrategy: opts.strategy,
    sellerStrategy: opts.sellerStrategy,
    status: opts.status ?? 'completed',
    rounds: opts.rounds.map((r) => ({
      roundNumber: r.roundNumber,
      proposedBy: r.proposedBy,
      priceOffered: r.priceOffered,
      unit: r.unit,
      message: r.message,
      timestamp: iso(-r.minutesAgo),
      autoGenerated: true,
    })),
    agreedPrice: opts.agreedPrice,
    agreedUnit: opts.unit,
    contractDuration: opts.contractDuration,
    startedAt: iso(-opts.startedMinutesAgo),
    completedAt: iso(-(opts.startedMinutesAgo - opts.rounds.length)),
  }
  saveNegotiation(neg)
  return neg
}

export function seedEconomyDemo(): void {
  if (!isBrowser()) return
  if (localStorage.getItem(SEED_FLAG_KEY) === '1') return

  const milesight = mockDb.getAssets(MILESIGHT_ORG_ID)
  if (milesight.length === 0) return // not yet initialized

  // 1. Identities + wallets (500-2000 TC) — gated by individual thingId presence
  ensureIdentitiesForOrg(MILESIGHT_ORG_ID)

  // Deterministic pseudo-random per asset id to keep balances stable
  function pseudoRand(seed: string): number {
    let h = 2166136261 >>> 0
    for (let i = 0; i < seed.length; i++) {
      h ^= seed.charCodeAt(i)
      h = Math.imul(h, 16777619) >>> 0
    }
    return (h % 1000) / 1000
  }
  ensureWalletsForOrg(MILESIGHT_ORG_ID, (idx) => {
    const asset = milesight[idx]
    return Math.round(500 + pseudoRand(asset.id) * 1500)
  })

  // 2. Marketplace capabilities — only seed if empty for this org
  const existingCaps = listCapabilities({ orgId: MILESIGHT_ORG_ID })
  if (existingCaps.length === 0) {
    // Offers
    createCapability({ thingId: 'ast_ms_05', orgId: MILESIGHT_ORG_ID, template: tpl('Temperature Data'), icon: '🌡️' })
    createCapability({ thingId: 'ast_ms_12', orgId: MILESIGHT_ORG_ID, template: tpl('Humidity Data') })
    createCapability({ thingId: 'ast_ms_03', orgId: MILESIGHT_ORG_ID, template: tpl('Air Quality Data') })
    createCapability({ thingId: 'ast_ms_37', orgId: MILESIGHT_ORG_ID, template: tpl('Edge Compute') })
    createCapability({ thingId: 'ast_ms_39', orgId: MILESIGHT_ORG_ID, template: tpl('Solar Energy Surplus') })
    createCapability({ thingId: 'ast_ms_40', orgId: MILESIGHT_ORG_ID, template: tpl('Valve Control') })
    createCapability({ thingId: 'ast_ms_38', orgId: MILESIGHT_ORG_ID, template: tpl('LoRa Gateway Relay') })
    // Needs
    createCapability({ thingId: 'ast_ms_37', orgId: MILESIGHT_ORG_ID, template: tpl('Internet Uplink') })
    createCapability({ thingId: 'ast_ms_40', orgId: MILESIGHT_ORG_ID, template: tpl('Power Supply') })
  }

  // 3. Historical transactions — derived from seeded negotiations below.
  //    We also add a handful of generic transactions so the wallet feed looks alive.
  const existingTxs = listTransactions()
  const sellers = ['ast_ms_05', 'ast_ms_12', 'ast_ms_03', 'ast_ms_37', 'ast_ms_39']
  const buyers = ['ast_ms_40', 'ast_ms_38', 'ast_ms_29', 'ast_ms_22']
  if (existingTxs.length === 0) {
    const sampleTypes: Array<[string, number, string]> = [
      ['data_purchase', 5, 'Temperature data batch'],
      ['data_purchase', 3, 'Humidity data batch'],
      ['compute_job', 10, 'Edge compute hour'],
      ['service_payment', 8, 'Valve actuation event'],
      ['energy_trade', 6, 'Solar surplus'],
      ['resolution_fee', 0.5, 'ThingDaddy resolver fee'],
      ['data_purchase', 4, 'Air quality data batch'],
      ['service_payment', 2, 'LoRa relay messages'],
      ['compute_job', 12, 'ML inference job'],
      ['data_purchase', 5, 'Temperature data batch'],
    ]
    sampleTypes.forEach(([type, amount, desc], i) => {
      const seller = sellers[i % sellers.length]
      const buyer = buyers[i % buyers.length]
      transfer({
        fromThingId: buyer,
        toThingId: seller,
        amount,
        type: type as 'data_purchase',
        description: desc,
        force: true,
        createdAt: iso(-(5 + i * 37)),
      })
    })
  }

  // 4. Three seeded negotiations with populated rounds
  const existingNegs = listNegotiations(MILESIGHT_ORG_ID)
  let seededNeg1 = existingNegs.find((n) => n.id === 'neg_seed_01')
  let seededNeg2 = existingNegs.find((n) => n.id === 'neg_seed_02')
  let seededNeg3 = existingNegs.find((n) => n.id === 'neg_seed_03')

  if (!seededNeg1) {
    const temp = listCapabilities({ orgId: MILESIGHT_ORG_ID, direction: 'offer' }).find(
      (c) => c.name === 'Temperature Data',
    )
    if (temp) {
      seededNeg1 = seedNegotiationRecord({
        id: 'neg_seed_01',
        orgId: MILESIGHT_ORG_ID,
        buyerThingId: 'ast_ms_37', // UG65 gateway
        sellerThingId: 'ast_ms_05', // VS121
        capabilityId: temp.id,
        capabilityName: temp.name,
        capabilityIcon: temp.icon,
        unit: temp.unit,
        listedPrice: 5,
        buyerBudget: 4,
        sellerMinAccept: 2.5,
        strategy: 'balanced',
        sellerStrategy: 'balanced',
        contractDuration: '7 days',
        startedMinutesAgo: 180,
        agreedPrice: 3,
        rounds: [
          { roundNumber: 1, proposedBy: 'seller', priceOffered: 5, unit: temp.unit, message: 'Listed at 5 TC / 1000 readings', minutesAgo: 180 },
          { roundNumber: 2, proposedBy: 'buyer', priceOffered: 2, unit: temp.unit, message: 'Counter: 2 TC / 1000 readings', minutesAgo: 179 },
          { roundNumber: 3, proposedBy: 'seller', priceOffered: 4, unit: temp.unit, message: 'Counter: 4 TC / 1000 readings', minutesAgo: 178 },
          { roundNumber: 4, proposedBy: 'buyer', priceOffered: 3, unit: temp.unit, message: 'Counter: 3 TC / 1000 readings', minutesAgo: 177 },
          { roundNumber: 5, proposedBy: 'seller', priceOffered: 3, unit: temp.unit, message: 'Accept: 3 TC / 1000 readings', minutesAgo: 176 },
          { roundNumber: 6, proposedBy: 'buyer', priceOffered: 3, unit: temp.unit, message: '✓ Deal at 3 TC / 1000 readings', minutesAgo: 175 },
        ],
      })
    }
  }

  if (!seededNeg2) {
    const compute = listCapabilities({ orgId: MILESIGHT_ORG_ID, direction: 'offer' }).find(
      (c) => c.name === 'Edge Compute',
    )
    if (compute) {
      seededNeg2 = seedNegotiationRecord({
        id: 'neg_seed_02',
        orgId: MILESIGHT_ORG_ID,
        buyerThingId: 'ast_ms_40', // UC300
        sellerThingId: 'ast_ms_37', // UG65
        capabilityId: compute.id,
        capabilityName: compute.name,
        capabilityIcon: compute.icon,
        unit: compute.unit,
        listedPrice: 10,
        buyerBudget: 9,
        sellerMinAccept: 6,
        strategy: 'aggressive',
        sellerStrategy: 'aggressive',
        contractDuration: 'Ongoing',
        startedMinutesAgo: 480,
        agreedPrice: 8,
        rounds: [
          { roundNumber: 1, proposedBy: 'seller', priceOffered: 10, unit: compute.unit, message: 'Listed at 10 TC / hour', minutesAgo: 480 },
          { roundNumber: 2, proposedBy: 'buyer', priceOffered: 2.7, unit: compute.unit, message: 'Counter: 2.7 TC / hour', minutesAgo: 479 },
          { roundNumber: 3, proposedBy: 'seller', priceOffered: 9.6, unit: compute.unit, message: 'Counter: 9.6 TC / hour', minutesAgo: 478 },
          { roundNumber: 4, proposedBy: 'buyer', priceOffered: 3.6, unit: compute.unit, message: 'Counter: 3.6 TC / hour', minutesAgo: 477 },
          { roundNumber: 5, proposedBy: 'seller', priceOffered: 9.2, unit: compute.unit, message: 'Counter: 9.2 TC / hour', minutesAgo: 476 },
          { roundNumber: 6, proposedBy: 'buyer', priceOffered: 8, unit: compute.unit, message: 'Counter: 8 TC / hour', minutesAgo: 475 },
          { roundNumber: 7, proposedBy: 'seller', priceOffered: 8, unit: compute.unit, message: 'Accept: 8 TC / hour', minutesAgo: 474 },
          { roundNumber: 8, proposedBy: 'buyer', priceOffered: 8, unit: compute.unit, message: '✓ Deal at 8 TC / hour', minutesAgo: 473 },
        ],
      })
    }
  }

  if (!seededNeg3) {
    const energy = listCapabilities({ orgId: MILESIGHT_ORG_ID, direction: 'offer' }).find(
      (c) => c.name === 'Solar Energy Surplus',
    )
    if (energy) {
      seededNeg3 = seedNegotiationRecord({
        id: 'neg_seed_03',
        orgId: MILESIGHT_ORG_ID,
        buyerThingId: 'ast_ms_40', // UC300
        sellerThingId: 'ast_ms_39', // SG50 solar gateway
        capabilityId: energy.id,
        capabilityName: energy.name,
        capabilityIcon: energy.icon,
        unit: energy.unit,
        listedPrice: 2,
        buyerBudget: 2.5,
        sellerMinAccept: 2,
        strategy: 'fixed',
        sellerStrategy: 'fixed',
        contractDuration: 'until sunset',
        startedMinutesAgo: 60,
        agreedPrice: 2,
        rounds: [
          { roundNumber: 1, proposedBy: 'seller', priceOffered: 2, unit: energy.unit, message: 'Fixed price: 2 TC / kWh', minutesAgo: 60 },
          { roundNumber: 2, proposedBy: 'buyer', priceOffered: 2, unit: energy.unit, message: 'Accept: 2 TC / kWh', minutesAgo: 59 },
          { roundNumber: 3, proposedBy: 'seller', priceOffered: 2, unit: energy.unit, message: '✓ Deal at 2 TC / kWh', minutesAgo: 58 },
        ],
      })
    }
  }

  // 5. Two active contracts linked to the first two negotiations
  const existingContracts = listContracts(MILESIGHT_ORG_ID)
  let contract1 = existingContracts.find((c) => c.id === 'ct_seed_01')
  let contract2 = existingContracts.find((c) => c.id === 'ct_seed_02')
  if (!contract1 && seededNeg1) {
    contract1 = createContract({
      negotiationId: seededNeg1.id,
      orgId: MILESIGHT_ORG_ID,
      buyerThingId: seededNeg1.buyerThingId,
      sellerThingId: seededNeg1.sellerThingId,
      capabilityId: seededNeg1.capabilityId,
      capabilityName: seededNeg1.capabilityName,
      capabilityIcon: seededNeg1.capabilityIcon,
      agreedPrice: seededNeg1.agreedPrice ?? 3,
      unit: seededNeg1.unit,
      durationLabel: '7 days',
      startedAt: iso(-175),
      deliveredUnits: 45,
      costAccrued: 135,
      uptimePct: 99.2,
    })
    contract1 = { ...contract1, id: 'ct_seed_01' }
    // Patch id to stable seed id
  }
  if (!contract2 && seededNeg2) {
    contract2 = createContract({
      negotiationId: seededNeg2.id,
      orgId: MILESIGHT_ORG_ID,
      buyerThingId: seededNeg2.buyerThingId,
      sellerThingId: seededNeg2.sellerThingId,
      capabilityId: seededNeg2.capabilityId,
      capabilityName: seededNeg2.capabilityName,
      capabilityIcon: seededNeg2.capabilityIcon,
      agreedPrice: seededNeg2.agreedPrice ?? 8,
      unit: seededNeg2.unit,
      durationLabel: 'Ongoing',
      startedAt: iso(-473),
      deliveredUnits: 60,
      costAccrued: 480,
      uptimePct: 99.2,
    })
  }

  // 6. Ratings (5 total, mix of scores)
  if (listRatings().length === 0 && contract1 && contract2) {
    createRating({ contractId: contract1.id, raterThingId: contract1.buyerThingId, ratedThingId: contract1.sellerThingId, rating: 5, comment: 'Perfect uptime' })
    createRating({ contractId: contract1.id, raterThingId: contract1.sellerThingId, ratedThingId: contract1.buyerThingId, rating: 5, comment: 'Paid promptly' })
    createRating({ contractId: contract2.id, raterThingId: contract2.buyerThingId, ratedThingId: contract2.sellerThingId, rating: 4, comment: 'Good compute throughput' })
    createRating({ contractId: contract2.id, raterThingId: contract2.sellerThingId, ratedThingId: contract2.buyerThingId, rating: 4, comment: 'Reliable buyer' })
    createRating({ contractId: contract1.id, raterThingId: 'ast_ms_38', ratedThingId: contract1.sellerThingId, rating: 3, comment: 'Data latency spiked once' })
  }

  // 7. Dashboard notifications via rulesEngine
  const noteKey = 'economy:seeded'
  const notes = loadNotifications()
  if (!notes.some((n) => n.message.includes(noteKey))) {
    pushNotification({
      orgId: MILESIGHT_ORG_ID,
      message: '🤝 New contract: VS121 → UG65 temperature data feed at 3 TC/1000 readings (economy:seeded)',
      severity: 'info',
    })
    pushNotification({
      orgId: MILESIGHT_ORG_ID,
      message: '💰 UG65 earned 135 TC from temperature data sales today (economy:seeded)',
      severity: 'info',
    })
    pushNotification({
      orgId: MILESIGHT_ORG_ID,
      message: '☀️ SG50 solar gateway has 3.5 kWh surplus available for trade (economy:seeded)',
      severity: 'info',
    })
  }

  // Nudge wallets so UG65 has a realistic high balance for demo earning
  const ug65 = getWallet('ast_ms_37')
  if (ug65 && ug65.balance < 2000) {
    setWallet({ ...ug65, balance: 2000, totalEarned: 800 })
  }

  localStorage.setItem(SEED_FLAG_KEY, '1')
}
