import { getDidFor } from './deviceIdentity'
import { getCapability } from './capabilities'
import { transfer } from './deviceWallet'
import { createContract } from './contracts'

// ─── Types ───────────────────────────────────────────────

export type NegotiationStrategy = 'aggressive' | 'balanced' | 'generous' | 'fixed'

export type NegotiationStatus =
  | 'initiated'
  | 'negotiating'
  | 'accepted'
  | 'rejected'
  | 'expired'
  | 'completed'

export interface NegotiationRound {
  roundNumber: number
  proposedBy: 'buyer' | 'seller'
  priceOffered: number
  unit: string
  message?: string
  timestamp: string
  autoGenerated: boolean
}

export interface Negotiation {
  id: string
  orgId: string
  buyerThingId: string
  buyerDid: string
  sellerThingId: string
  sellerDid: string
  capabilityId: string
  capabilityName: string
  capabilityIcon: string
  unit: string
  listedPrice: number
  buyerBudget: number
  sellerMinAccept: number
  buyerStrategy: NegotiationStrategy
  sellerStrategy: NegotiationStrategy
  status: NegotiationStatus
  rounds: NegotiationRound[]
  agreedPrice?: number
  agreedUnit?: string
  contractDuration?: string
  transactionId?: string
  contractId?: string
  startedAt: string
  completedAt?: string
}

// ─── Storage ─────────────────────────────────────────────

const STORAGE_KEY = 'thingdaddy.economy.negotiations.v1'

function isBrowser(): boolean {
  return typeof window !== 'undefined'
}

function loadAll(): Negotiation[] {
  if (!isBrowser()) return []
  const raw = localStorage.getItem(STORAGE_KEY)
  if (!raw) return []
  try {
    return JSON.parse(raw) as Negotiation[]
  } catch {
    return []
  }
}

function saveAll(list: Negotiation[]): void {
  if (!isBrowser()) return
  localStorage.setItem(STORAGE_KEY, JSON.stringify(list))
}

function newId(): string {
  return isBrowser() && typeof crypto !== 'undefined' && 'randomUUID' in crypto
    ? `neg_${crypto.randomUUID().slice(0, 12)}`
    : `neg_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 6)}`
}

// ─── Strategies ──────────────────────────────────────────

export interface StrategyDescriptor {
  key: NegotiationStrategy
  label: string
  asSeller: string
  asBuyer: string
}

export const STRATEGIES: StrategyDescriptor[] = [
  {
    key: 'aggressive',
    label: 'Aggressive',
    asSeller: 'Start at listed, drop 10% max',
    asBuyer: 'Start at 30% of budget, raise slowly',
  },
  {
    key: 'balanced',
    label: 'Balanced',
    asSeller: 'Start at listed, drop 20% per round',
    asBuyer: 'Start at 50%, meet in the middle',
  },
  {
    key: 'generous',
    label: 'Generous',
    asSeller: 'Start at 80% of listed, flexible',
    asBuyer: 'Start at 80% of budget, quick deal',
  },
  {
    key: 'fixed',
    label: 'Fixed',
    asSeller: 'No negotiation — take it or leave it',
    asBuyer: 'Fixed offer — accept or walk away',
  },
]

function roundPrice(n: number): number {
  return Math.round(n * 100) / 100
}

function buyerOpeningPrice(budget: number, strategy: NegotiationStrategy): number {
  switch (strategy) {
    case 'aggressive':
      return roundPrice(budget * 0.3)
    case 'balanced':
      return roundPrice(budget * 0.5)
    case 'generous':
      return roundPrice(budget * 0.8)
    case 'fixed':
      return roundPrice(budget)
  }
}

function buyerNextPrice(prev: number, budget: number, strategy: NegotiationStrategy): number {
  switch (strategy) {
    case 'aggressive':
      return roundPrice(Math.min(budget, prev + (budget - prev) * 0.15))
    case 'balanced':
      return roundPrice(Math.min(budget, prev + (budget - prev) * 0.35))
    case 'generous':
      return roundPrice(Math.min(budget, prev + (budget - prev) * 0.6))
    case 'fixed':
      return roundPrice(budget)
  }
}

function sellerOpeningPrice(listed: number, strategy: NegotiationStrategy): number {
  switch (strategy) {
    case 'aggressive':
    case 'balanced':
    case 'fixed':
      return roundPrice(listed)
    case 'generous':
      return roundPrice(listed * 0.8)
  }
}

function sellerNextPrice(prev: number, minAccept: number, strategy: NegotiationStrategy): number {
  switch (strategy) {
    case 'aggressive':
      return roundPrice(Math.max(minAccept, prev - (prev - minAccept) * 0.1))
    case 'balanced':
      return roundPrice(Math.max(minAccept, prev * 0.8))
    case 'generous':
      return roundPrice(Math.max(minAccept, prev - (prev - minAccept) * 0.5))
    case 'fixed':
      return roundPrice(prev)
  }
}

// ─── Engine ──────────────────────────────────────────────

export interface RunNegotiationInput {
  orgId: string
  buyerThingId: string
  sellerThingId: string
  capabilityId: string
  buyerBudget: number
  sellerMinAccept?: number
  buyerStrategy?: NegotiationStrategy
  sellerStrategy?: NegotiationStrategy
  maxRounds?: number
  contractDuration?: string
  /** If true, persist to storage and trigger transfer/contract on accept. */
  persist?: boolean
}

export function runAutoNegotiation(input: RunNegotiationInput): Negotiation {
  const cap = getCapability(input.capabilityId)
  if (!cap) throw new Error(`capability not found: ${input.capabilityId}`)

  const listedPrice = cap.pricePerUnit
  const sellerMinAccept = input.sellerMinAccept ?? Math.max(1, listedPrice * 0.4)
  const buyerStrategy: NegotiationStrategy = input.buyerStrategy ?? 'balanced'
  const sellerStrategy: NegotiationStrategy = input.sellerStrategy ?? 'balanced'
  const maxRounds = input.maxRounds ?? 5

  const rounds: NegotiationRound[] = []
  const startedAt = new Date().toISOString()
  const neg: Negotiation = {
    id: newId(),
    orgId: input.orgId,
    buyerThingId: input.buyerThingId,
    buyerDid: getDidFor(input.buyerThingId),
    sellerThingId: input.sellerThingId,
    sellerDid: getDidFor(input.sellerThingId),
    capabilityId: cap.id,
    capabilityName: cap.name,
    capabilityIcon: cap.icon,
    unit: cap.unit,
    listedPrice,
    buyerBudget: input.buyerBudget,
    sellerMinAccept,
    buyerStrategy,
    sellerStrategy,
    status: 'initiated',
    rounds,
    startedAt,
    contractDuration: input.contractDuration ?? '7 days',
  }

  // Round 1: seller lists
  let sellerPrice = sellerOpeningPrice(listedPrice, sellerStrategy)
  rounds.push({
    roundNumber: 1,
    proposedBy: 'seller',
    priceOffered: sellerPrice,
    unit: cap.unit,
    message: `Listed at ${sellerPrice} TC / ${cap.unit}`,
    timestamp: new Date().toISOString(),
    autoGenerated: true,
  })

  // Round 2: buyer opens
  let buyerPrice = buyerOpeningPrice(input.buyerBudget, buyerStrategy)
  rounds.push({
    roundNumber: 2,
    proposedBy: 'buyer',
    priceOffered: buyerPrice,
    unit: cap.unit,
    message: `Counter: ${buyerPrice} TC / ${cap.unit}`,
    timestamp: new Date().toISOString(),
    autoGenerated: true,
  })

  neg.status = 'negotiating'

  let accepted = false
  let finalPrice = 0
  let acceptedBy: 'buyer' | 'seller' = 'buyer'

  // Alternate counter-offers
  for (let r = 3; r <= maxRounds + 2; r++) {
    const isSeller = r % 2 === 1 // r=3 seller, r=4 buyer, ...
    if (isSeller) {
      // Seller accepts if buyer's last offer >= min accept
      if (buyerPrice >= sellerMinAccept) {
        rounds.push({
          roundNumber: r,
          proposedBy: 'seller',
          priceOffered: buyerPrice,
          unit: cap.unit,
          message: `Accept: ${buyerPrice} TC / ${cap.unit}`,
          timestamp: new Date().toISOString(),
          autoGenerated: true,
        })
        accepted = true
        finalPrice = buyerPrice
        acceptedBy = 'seller'
        break
      }
      sellerPrice = sellerNextPrice(sellerPrice, sellerMinAccept, sellerStrategy)
      rounds.push({
        roundNumber: r,
        proposedBy: 'seller',
        priceOffered: sellerPrice,
        unit: cap.unit,
        message: `Counter: ${sellerPrice} TC / ${cap.unit}`,
        timestamp: new Date().toISOString(),
        autoGenerated: true,
      })
      if (sellerStrategy === 'fixed') break
    } else {
      // Buyer accepts if seller's last offer <= budget
      if (sellerPrice <= input.buyerBudget) {
        rounds.push({
          roundNumber: r,
          proposedBy: 'buyer',
          priceOffered: sellerPrice,
          unit: cap.unit,
          message: `Accept: ${sellerPrice} TC / ${cap.unit}`,
          timestamp: new Date().toISOString(),
          autoGenerated: true,
        })
        accepted = true
        finalPrice = sellerPrice
        acceptedBy = 'buyer'
        break
      }
      buyerPrice = buyerNextPrice(buyerPrice, input.buyerBudget, buyerStrategy)
      rounds.push({
        roundNumber: r,
        proposedBy: 'buyer',
        priceOffered: buyerPrice,
        unit: cap.unit,
        message: `Counter: ${buyerPrice} TC / ${cap.unit}`,
        timestamp: new Date().toISOString(),
        autoGenerated: true,
      })
      if (buyerStrategy === 'fixed') break
    }
  }

  if (accepted) {
    neg.status = 'accepted'
    neg.agreedPrice = finalPrice
    neg.agreedUnit = cap.unit
    neg.completedAt = new Date().toISOString()
    // Last-round deal confirmation
    rounds.push({
      roundNumber: rounds[rounds.length - 1].roundNumber + 1,
      proposedBy: acceptedBy,
      priceOffered: finalPrice,
      unit: cap.unit,
      message: `✓ Deal at ${finalPrice} TC / ${cap.unit}`,
      timestamp: new Date().toISOString(),
      autoGenerated: true,
    })
  } else {
    neg.status = 'rejected'
    neg.completedAt = new Date().toISOString()
  }

  if (input.persist) {
    saveNegotiation(neg)
    if (accepted) {
      // Execute the contract + transfer
      const contract = createContract({
        negotiationId: neg.id,
        orgId: input.orgId,
        buyerThingId: input.buyerThingId,
        sellerThingId: input.sellerThingId,
        capabilityId: cap.id,
        capabilityName: cap.name,
        capabilityIcon: cap.icon,
        agreedPrice: finalPrice,
        unit: cap.unit,
        durationLabel: neg.contractDuration ?? '7 days',
      })
      const tx = transfer({
        fromThingId: input.buyerThingId,
        toThingId: input.sellerThingId,
        amount: finalPrice,
        type: categoryToTxType(cap.category),
        description: `${cap.name} — negotiated at ${finalPrice} TC / ${cap.unit}`,
        negotiationId: neg.id,
        contractId: contract.id,
      })
      neg.contractId = contract.id
      neg.transactionId = tx.id
      neg.status = 'completed'
      updateNegotiation(neg.id, {
        contractId: contract.id,
        transactionId: tx.id,
        status: 'completed',
      })
    }
  }

  return neg
}

function categoryToTxType(category: string): 'data_purchase' | 'compute_job' | 'energy_trade' | 'service_payment' {
  switch (category) {
    case 'data':
      return 'data_purchase'
    case 'compute':
      return 'compute_job'
    case 'energy':
      return 'energy_trade'
    default:
      return 'service_payment'
  }
}

// ─── Storage API ─────────────────────────────────────────

export function saveNegotiation(neg: Negotiation): void {
  const all = loadAll()
  const i = all.findIndex((n) => n.id === neg.id)
  if (i === -1) saveAll([neg, ...all])
  else {
    all[i] = neg
    saveAll(all)
  }
}

export function updateNegotiation(id: string, updates: Partial<Negotiation>): Negotiation | undefined {
  const all = loadAll()
  const i = all.findIndex((n) => n.id === id)
  if (i === -1) return undefined
  const next = { ...all[i], ...updates, id: all[i].id }
  all[i] = next
  saveAll(all)
  return next
}

export function listNegotiations(orgId?: string): Negotiation[] {
  let all = loadAll()
  if (orgId) all = all.filter((n) => n.orgId === orgId)
  return [...all].sort((a, b) => b.startedAt.localeCompare(a.startedAt))
}

export function getNegotiation(id: string): Negotiation | undefined {
  return loadAll().find((n) => n.id === id)
}

export function seedNegotiation(neg: Negotiation): void {
  saveNegotiation(neg)
}
