/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThingThingIdRouteImport } from './routes/thing.$thingId'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as AuthTransfersRouteImport } from './routes/_auth/transfers'
import { Route as AuthSearchAssetsRouteImport } from './routes/_auth/search-assets'
import { Route as AuthListRouteImport } from './routes/_auth/list'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthCreateRouteImport } from './routes/_auth/create'
import { Route as AuthBatchImportRouteImport } from './routes/_auth/batch-import'
import { Route as AuthAuditLogsRouteImport } from './routes/_auth/audit-logs'
import { Route as ThingThingIdCertificateRouteImport } from './routes/thing.$thingId.certificate'
import { Route as ThingThingIdActivateRouteImport } from './routes/thing.$thingId.activate'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings_.profile'
import { Route as AuthSettingsOrganizationRouteImport } from './routes/_auth/settings_.organization'
import { Route as AuthAdminFeaturesRouteImport } from './routes/_auth/admin_.features'
import { Route as AuthListAssetIdRouteImport } from './routes/_auth/list_.$assetId'
import { Route as AuthCloudResolverRouteImport } from './routes/_auth/cloud_.resolver'
import { Route as AuthCloudMessengerRouteImport } from './routes/_auth/cloud_.messenger'
import { Route as AuthRulesRouteImport } from './routes/_auth/rules'
import { Route as AuthRulesCreateRouteImport } from './routes/_auth/rules_.create'
import { Route as AuthRulesSimulatorRouteImport } from './routes/_auth/rules_.simulator'
import { Route as AuthRulesRuleIdRouteImport } from './routes/_auth/rules_.$ruleId'
import { Route as AuthDiscoveryRouteImport } from './routes/_auth/discovery'
import { Route as AuthDiscoveryTopologyRouteImport } from './routes/_auth/discovery_.topology'
import { Route as AuthEconomyRouteImport } from './routes/_auth/economy'
import { Route as AuthEconomyMarketplaceRouteImport } from './routes/_auth/economy_.marketplace'
import { Route as AuthEconomyNegotiationsRouteImport } from './routes/_auth/economy_.negotiations'
import { Route as AuthEconomyContractsRouteImport } from './routes/_auth/economy_.contracts'
import { Route as R01Gtin21SerialRouteImport } from './routes/01.$gtin.21.$serial'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThingThingIdRoute = ThingThingIdRouteImport.update({
  id: '/thing/$thingId',
  path: '/thing/$thingId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTransfersRoute = AuthTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSearchAssetsRoute = AuthSearchAssetsRouteImport.update({
  id: '/search-assets',
  path: '/search-assets',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthListRoute = AuthListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCreateRoute = AuthCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthBatchImportRoute = AuthBatchImportRouteImport.update({
  id: '/batch-import',
  path: '/batch-import',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuditLogsRoute = AuthAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ThingThingIdCertificateRoute = ThingThingIdCertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => ThingThingIdRoute,
} as any)
const ThingThingIdActivateRoute = ThingThingIdActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => ThingThingIdRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/settings_/profile',
  path: '/settings/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsOrganizationRoute =
  AuthSettingsOrganizationRouteImport.update({
    id: '/settings_/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAdminFeaturesRoute = AuthAdminFeaturesRouteImport.update({
  id: '/admin_/features',
  path: '/admin/features',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthListAssetIdRoute = AuthListAssetIdRouteImport.update({
  id: '/list_/$assetId',
  path: '/list/$assetId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCloudResolverRoute = AuthCloudResolverRouteImport.update({
  id: '/cloud_/resolver',
  path: '/cloud/resolver',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCloudMessengerRoute = AuthCloudMessengerRouteImport.update({
  id: '/cloud_/messenger',
  path: '/cloud/messenger',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRulesRoute = AuthRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRulesCreateRoute = AuthRulesCreateRouteImport.update({
  id: '/rules_/create',
  path: '/rules/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRulesSimulatorRoute = AuthRulesSimulatorRouteImport.update({
  id: '/rules_/simulator',
  path: '/rules/simulator',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRulesRuleIdRoute = AuthRulesRuleIdRouteImport.update({
  id: '/rules_/$ruleId',
  path: '/rules/$ruleId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDiscoveryRoute = AuthDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDiscoveryTopologyRoute = AuthDiscoveryTopologyRouteImport.update({
  id: '/discovery_/topology',
  path: '/discovery/topology',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEconomyRoute = AuthEconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEconomyMarketplaceRoute = AuthEconomyMarketplaceRouteImport.update({
  id: '/economy_/marketplace',
  path: '/economy/marketplace',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEconomyNegotiationsRoute = AuthEconomyNegotiationsRouteImport.update({
  id: '/economy_/negotiations',
  path: '/economy/negotiations',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEconomyContractsRoute = AuthEconomyContractsRouteImport.update({
  id: '/economy_/contracts',
  path: '/economy/contracts',
  getParentRoute: () => AuthRouteRoute,
} as any)
const R01Gtin21SerialRoute = R01Gtin21SerialRouteImport.update({
  id: '/01/$gtin/21/$serial',
  path: '/01/$gtin/21/$serial',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/audit-logs': typeof AuthAuditLogsRoute
  '/batch-import': typeof AuthBatchImportRoute
  '/create': typeof AuthCreateRoute
  '/dashboard': typeof AuthDashboardRoute
  '/list': typeof AuthListRoute
  '/search-assets': typeof AuthSearchAssetsRoute
  '/transfers': typeof AuthTransfersRoute
  '/demo/table': typeof DemoTableRoute
  '/thing/$thingId': typeof ThingThingIdRouteWithChildren
  '/cloud/messenger': typeof AuthCloudMessengerRoute
  '/cloud/resolver': typeof AuthCloudResolverRoute
  '/rules': typeof AuthRulesRoute
  '/rules/create': typeof AuthRulesCreateRoute
  '/rules/simulator': typeof AuthRulesSimulatorRoute
  '/rules/$ruleId': typeof AuthRulesRuleIdRoute
  '/discovery': typeof AuthDiscoveryRoute
  '/discovery/topology': typeof AuthDiscoveryTopologyRoute
  '/economy': typeof AuthEconomyRoute
  '/economy/marketplace': typeof AuthEconomyMarketplaceRoute
  '/economy/negotiations': typeof AuthEconomyNegotiationsRoute
  '/economy/contracts': typeof AuthEconomyContractsRoute
  '/list/$assetId': typeof AuthListAssetIdRoute
  '/settings/organization': typeof AuthSettingsOrganizationRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/admin/features': typeof AuthAdminFeaturesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/thing/$thingId/activate': typeof ThingThingIdActivateRoute
  '/thing/$thingId/certificate': typeof ThingThingIdCertificateRoute
  '/01/$gtin/21/$serial': typeof R01Gtin21SerialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/audit-logs': typeof AuthAuditLogsRoute
  '/batch-import': typeof AuthBatchImportRoute
  '/create': typeof AuthCreateRoute
  '/dashboard': typeof AuthDashboardRoute
  '/list': typeof AuthListRoute
  '/search-assets': typeof AuthSearchAssetsRoute
  '/transfers': typeof AuthTransfersRoute
  '/demo/table': typeof DemoTableRoute
  '/thing/$thingId': typeof ThingThingIdRouteWithChildren
  '/cloud/messenger': typeof AuthCloudMessengerRoute
  '/cloud/resolver': typeof AuthCloudResolverRoute
  '/rules': typeof AuthRulesRoute
  '/rules/create': typeof AuthRulesCreateRoute
  '/rules/simulator': typeof AuthRulesSimulatorRoute
  '/rules/$ruleId': typeof AuthRulesRuleIdRoute
  '/discovery': typeof AuthDiscoveryRoute
  '/discovery/topology': typeof AuthDiscoveryTopologyRoute
  '/economy': typeof AuthEconomyRoute
  '/economy/marketplace': typeof AuthEconomyMarketplaceRoute
  '/economy/negotiations': typeof AuthEconomyNegotiationsRoute
  '/economy/contracts': typeof AuthEconomyContractsRoute
  '/list/$assetId': typeof AuthListAssetIdRoute
  '/settings/organization': typeof AuthSettingsOrganizationRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/admin/features': typeof AuthAdminFeaturesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/thing/$thingId/activate': typeof ThingThingIdActivateRoute
  '/thing/$thingId/certificate': typeof ThingThingIdCertificateRoute
  '/01/$gtin/21/$serial': typeof R01Gtin21SerialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/_auth/audit-logs': typeof AuthAuditLogsRoute
  '/_auth/batch-import': typeof AuthBatchImportRoute
  '/_auth/create': typeof AuthCreateRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/list': typeof AuthListRoute
  '/_auth/search-assets': typeof AuthSearchAssetsRoute
  '/_auth/transfers': typeof AuthTransfersRoute
  '/demo/table': typeof DemoTableRoute
  '/thing/$thingId': typeof ThingThingIdRouteWithChildren
  '/_auth/cloud_/messenger': typeof AuthCloudMessengerRoute
  '/_auth/cloud_/resolver': typeof AuthCloudResolverRoute
  '/_auth/rules': typeof AuthRulesRoute
  '/_auth/rules_/create': typeof AuthRulesCreateRoute
  '/_auth/rules_/simulator': typeof AuthRulesSimulatorRoute
  '/_auth/rules_/$ruleId': typeof AuthRulesRuleIdRoute
  '/_auth/discovery': typeof AuthDiscoveryRoute
  '/_auth/discovery_/topology': typeof AuthDiscoveryTopologyRoute
  '/_auth/economy': typeof AuthEconomyRoute
  '/_auth/economy_/marketplace': typeof AuthEconomyMarketplaceRoute
  '/_auth/economy_/negotiations': typeof AuthEconomyNegotiationsRoute
  '/_auth/economy_/contracts': typeof AuthEconomyContractsRoute
  '/_auth/list_/$assetId': typeof AuthListAssetIdRoute
  '/_auth/settings_/organization': typeof AuthSettingsOrganizationRoute
  '/_auth/settings_/profile': typeof AuthSettingsProfileRoute
  '/_auth/admin_/features': typeof AuthAdminFeaturesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/thing/$thingId/activate': typeof ThingThingIdActivateRoute
  '/thing/$thingId/certificate': typeof ThingThingIdCertificateRoute
  '/01/$gtin/21/$serial': typeof R01Gtin21SerialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/audit-logs'
    | '/batch-import'
    | '/create'
    | '/dashboard'
    | '/list'
    | '/search-assets'
    | '/transfers'
    | '/demo/table'
    | '/thing/$thingId'
    | '/cloud/messenger'
    | '/cloud/resolver'
    | '/rules'
    | '/rules/create'
    | '/rules/simulator'
    | '/rules/$ruleId'
    | '/discovery'
    | '/discovery/topology'
    | '/economy'
    | '/economy/marketplace'
    | '/economy/negotiations'
    | '/economy/contracts'
    | '/list/$assetId'
    | '/settings/organization'
    | '/settings/profile'
    | '/admin/features'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/thing/$thingId/activate'
    | '/thing/$thingId/certificate'
    | '/01/$gtin/21/$serial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/audit-logs'
    | '/batch-import'
    | '/create'
    | '/dashboard'
    | '/list'
    | '/search-assets'
    | '/transfers'
    | '/demo/table'
    | '/thing/$thingId'
    | '/cloud/messenger'
    | '/cloud/resolver'
    | '/rules'
    | '/rules/create'
    | '/rules/simulator'
    | '/rules/$ruleId'
    | '/discovery'
    | '/discovery/topology'
    | '/economy'
    | '/economy/marketplace'
    | '/economy/negotiations'
    | '/economy/contracts'
    | '/list/$assetId'
    | '/settings/organization'
    | '/settings/profile'
    | '/admin/features'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/thing/$thingId/activate'
    | '/thing/$thingId/certificate'
    | '/01/$gtin/21/$serial'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/search'
    | '/_auth/audit-logs'
    | '/_auth/batch-import'
    | '/_auth/create'
    | '/_auth/dashboard'
    | '/_auth/list'
    | '/_auth/search-assets'
    | '/_auth/transfers'
    | '/demo/table'
    | '/thing/$thingId'
    | '/_auth/cloud_/messenger'
    | '/_auth/cloud_/resolver'
    | '/_auth/rules'
    | '/_auth/rules_/create'
    | '/_auth/rules_/simulator'
    | '/_auth/rules_/$ruleId'
    | '/_auth/discovery'
    | '/_auth/discovery_/topology'
    | '/_auth/economy'
    | '/_auth/economy_/marketplace'
    | '/_auth/economy_/negotiations'
    | '/_auth/economy_/contracts'
    | '/_auth/list_/$assetId'
    | '/_auth/settings_/organization'
    | '/_auth/settings_/profile'
    | '/_auth/admin_/features'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/thing/$thingId/activate'
    | '/thing/$thingId/certificate'
    | '/01/$gtin/21/$serial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  DemoTableRoute: typeof DemoTableRoute
  ThingThingIdRoute: typeof ThingThingIdRouteWithChildren
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  R01Gtin21SerialRoute: typeof R01Gtin21SerialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thing/$thingId': {
      id: '/thing/$thingId'
      path: '/thing/$thingId'
      fullPath: '/thing/$thingId'
      preLoaderRoute: typeof ThingThingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/transfers': {
      id: '/_auth/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthTransfersRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/search-assets': {
      id: '/_auth/search-assets'
      path: '/search-assets'
      fullPath: '/search-assets'
      preLoaderRoute: typeof AuthSearchAssetsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/list': {
      id: '/_auth/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof AuthListRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/create': {
      id: '/_auth/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/batch-import': {
      id: '/_auth/batch-import'
      path: '/batch-import'
      fullPath: '/batch-import'
      preLoaderRoute: typeof AuthBatchImportRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/audit-logs': {
      id: '/_auth/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthAuditLogsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/thing/$thingId/certificate': {
      id: '/thing/$thingId/certificate'
      path: '/certificate'
      fullPath: '/thing/$thingId/certificate'
      preLoaderRoute: typeof ThingThingIdCertificateRouteImport
      parentRoute: typeof ThingThingIdRoute
    }
    '/thing/$thingId/activate': {
      id: '/thing/$thingId/activate'
      path: '/activate'
      fullPath: '/thing/$thingId/activate'
      preLoaderRoute: typeof ThingThingIdActivateRouteImport
      parentRoute: typeof ThingThingIdRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings_/profile': {
      id: '/_auth/settings_/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings_/organization': {
      id: '/_auth/settings_/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthSettingsOrganizationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin_/features': {
      id: '/_auth/admin_/features'
      path: '/admin/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AuthAdminFeaturesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/list_/$assetId': {
      id: '/_auth/list_/$assetId'
      path: '/list/$assetId'
      fullPath: '/list/$assetId'
      preLoaderRoute: typeof AuthListAssetIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/cloud_/resolver': {
      id: '/_auth/cloud_/resolver'
      path: '/cloud/resolver'
      fullPath: '/cloud/resolver'
      preLoaderRoute: typeof AuthCloudResolverRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/cloud_/messenger': {
      id: '/_auth/cloud_/messenger'
      path: '/cloud/messenger'
      fullPath: '/cloud/messenger'
      preLoaderRoute: typeof AuthCloudMessengerRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/rules': {
      id: '/_auth/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AuthRulesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/rules_/create': {
      id: '/_auth/rules_/create'
      path: '/rules/create'
      fullPath: '/rules/create'
      preLoaderRoute: typeof AuthRulesCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/rules_/simulator': {
      id: '/_auth/rules_/simulator'
      path: '/rules/simulator'
      fullPath: '/rules/simulator'
      preLoaderRoute: typeof AuthRulesSimulatorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/rules_/$ruleId': {
      id: '/_auth/rules_/$ruleId'
      path: '/rules/$ruleId'
      fullPath: '/rules/$ruleId'
      preLoaderRoute: typeof AuthRulesRuleIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/discovery': {
      id: '/_auth/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthDiscoveryRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/discovery_/topology': {
      id: '/_auth/discovery_/topology'
      path: '/discovery/topology'
      fullPath: '/discovery/topology'
      preLoaderRoute: typeof AuthDiscoveryTopologyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/economy': {
      id: '/_auth/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof AuthEconomyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/economy_/marketplace': {
      id: '/_auth/economy_/marketplace'
      path: '/economy/marketplace'
      fullPath: '/economy/marketplace'
      preLoaderRoute: typeof AuthEconomyMarketplaceRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/economy_/negotiations': {
      id: '/_auth/economy_/negotiations'
      path: '/economy/negotiations'
      fullPath: '/economy/negotiations'
      preLoaderRoute: typeof AuthEconomyNegotiationsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/economy_/contracts': {
      id: '/_auth/economy_/contracts'
      path: '/economy/contracts'
      fullPath: '/economy/contracts'
      preLoaderRoute: typeof AuthEconomyContractsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/01/$gtin/21/$serial': {
      id: '/01/$gtin/21/$serial'
      path: '/01/$gtin/21/$serial'
      fullPath: '/01/$gtin/21/$serial'
      preLoaderRoute: typeof R01Gtin21SerialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAuditLogsRoute: typeof AuthAuditLogsRoute
  AuthBatchImportRoute: typeof AuthBatchImportRoute
  AuthCreateRoute: typeof AuthCreateRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthListRoute: typeof AuthListRoute
  AuthSearchAssetsRoute: typeof AuthSearchAssetsRoute
  AuthTransfersRoute: typeof AuthTransfersRoute
  AuthCloudMessengerRoute: typeof AuthCloudMessengerRoute
  AuthCloudResolverRoute: typeof AuthCloudResolverRoute
  AuthRulesRoute: typeof AuthRulesRoute
  AuthRulesCreateRoute: typeof AuthRulesCreateRoute
  AuthRulesSimulatorRoute: typeof AuthRulesSimulatorRoute
  AuthRulesRuleIdRoute: typeof AuthRulesRuleIdRoute
  AuthDiscoveryRoute: typeof AuthDiscoveryRoute
  AuthDiscoveryTopologyRoute: typeof AuthDiscoveryTopologyRoute
  AuthEconomyRoute: typeof AuthEconomyRoute
  AuthEconomyMarketplaceRoute: typeof AuthEconomyMarketplaceRoute
  AuthEconomyNegotiationsRoute: typeof AuthEconomyNegotiationsRoute
  AuthEconomyContractsRoute: typeof AuthEconomyContractsRoute
  AuthListAssetIdRoute: typeof AuthListAssetIdRoute
  AuthSettingsOrganizationRoute: typeof AuthSettingsOrganizationRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthAdminFeaturesRoute: typeof AuthAdminFeaturesRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuditLogsRoute: AuthAuditLogsRoute,
  AuthBatchImportRoute: AuthBatchImportRoute,
  AuthCreateRoute: AuthCreateRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthListRoute: AuthListRoute,
  AuthSearchAssetsRoute: AuthSearchAssetsRoute,
  AuthTransfersRoute: AuthTransfersRoute,
  AuthCloudMessengerRoute: AuthCloudMessengerRoute,
  AuthCloudResolverRoute: AuthCloudResolverRoute,
  AuthRulesRoute: AuthRulesRoute,
  AuthRulesCreateRoute: AuthRulesCreateRoute,
  AuthRulesSimulatorRoute: AuthRulesSimulatorRoute,
  AuthRulesRuleIdRoute: AuthRulesRuleIdRoute,
  AuthDiscoveryRoute: AuthDiscoveryRoute,
  AuthDiscoveryTopologyRoute: AuthDiscoveryTopologyRoute,
  AuthEconomyRoute: AuthEconomyRoute,
  AuthEconomyMarketplaceRoute: AuthEconomyMarketplaceRoute,
  AuthEconomyNegotiationsRoute: AuthEconomyNegotiationsRoute,
  AuthEconomyContractsRoute: AuthEconomyContractsRoute,
  AuthListAssetIdRoute: AuthListAssetIdRoute,
  AuthSettingsOrganizationRoute: AuthSettingsOrganizationRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthAdminFeaturesRoute: AuthAdminFeaturesRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ThingThingIdRouteChildren {
  ThingThingIdActivateRoute: typeof ThingThingIdActivateRoute
  ThingThingIdCertificateRoute: typeof ThingThingIdCertificateRoute
}

const ThingThingIdRouteChildren: ThingThingIdRouteChildren = {
  ThingThingIdActivateRoute: ThingThingIdActivateRoute,
  ThingThingIdCertificateRoute: ThingThingIdCertificateRoute,
}

const ThingThingIdRouteWithChildren = ThingThingIdRoute._addFileChildren(
  ThingThingIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  DemoTableRoute: DemoTableRoute,
  ThingThingIdRoute: ThingThingIdRouteWithChildren,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  R01Gtin21SerialRoute: R01Gtin21SerialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
